name: Carrey.ai Debug Agent

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Carrey-Dashboard/project # ✅ Fix path

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Debug Agent
        run: npm run debug-check

      - name: Run Token Usage Checker
        run: npm run debug-tokens
